version: "3.8"

services:
  backend:
    build: .
    container_name: planning-poker-backend
    ports:
      - "3001:3001"
    volumes:
      - ./src:/app/src
      - ./tsconfig.json:/app/tsconfig.json
      - ./nest-cli.json:/app/nest-cli.json
    command: npm run start:dev